name: neao_use_case
dependencies:
  - python == 3.9
  - scipy
  - numpy
  - matplotlib
  - pip
  - pip:
    - nixio
    - neo
    - elephant==0.14.0
    - viziphant
    - odml
    - multipledispatch
    - gastrodon
    - pytest
    - alpaca-prov==0.2.0
